### ISSUE TITLE
Add Compatability to M2035-LE Series of cameras

### ISSUE THREAD

**Issue by justinmiller62** [AxisCommunications/docker-acap#119]
### Describe the feature

This would be great if it was compatible with and available to use on the Axis M2035-LE series of cameras

### Added value

I would be able to do some management software on the edge for the camera and possible run some light ML models.

**Comment by madelen-axis** [comment]
Hi @justinmiller62, thank you for reaching out. 
Unfortunately the M20-series does not have container support and is therefore not compatible with running the Docker ACAP.
To find out more about compatible models see [Axis devices & compatibility](https://axiscommunications.github.io/acap-documentation/docs/axis-devices-and-compatibility/) in the ACAP SDK Documentation.
