### ISSUE TITLE
AXIS 1465-LE9 support acap?

### ISSUE THREAD

**Issue by Shaiken** [AxisCommunications/docker-acap#254]
I tried to update the firmware, but I don't know how to let docker enter the camera.

{
  "apiVersion": "1.3",
  "data": {
    "propertyList": {
      "Architecture": "aarch64",
      "ProdNbr": "P1465-LE",
      "HardwareID": "930",
      "ProdFullName": "AXIS P1465-LE Bullet Camera",
      "Version": "11.9.60",
      "ProdType": "Bullet Camera",
      "SocSerialNumber": "***",
      "Soc": "Axis Artpec-8",
      "Brand": "AXIS",
      "WebURL": "http://www.axis.com",
      "ProdVariant": "9mm",
      "SerialNumber": "***",
      "ProdShortName": "AXIS P1465-LE",
      "BuildDate": "Feb 23 2024 21:36"
    }
  },
  "context": "Client defined request ID"
}

I try to use this example
https://github.com/AxisCommunications/acap-computer-vision-sdk-examples/tree/main/hello-world-python

My host platform is windows
Use powershell to run,
But Set your device IP address and clear Docker memory I don’t know how to do it

**Comment by madelen-at-work** [comment]
Hi @Shaiken, 
Could you please provide more details on what you have tried and what settings you are using for the Docker ACAP application.

**Comment by Shaiken** [comment]
Thank you for your assistance. I've tried the examples from acap-native-sdk-examples and they all work, but integrating into my own docker is a bit difficult. In addition to the Dockerfile, I also need to pay attention to the Makefile. It doesn't go very well when converting c to cpp and using vod +opencv because I want to use a piecewise model, so can't just use axoverlay either.
Later I saw that acap-computer-vision-sdk-examples can use flask to call each other. Although it seems that it cannot be compared with the speed of acap-native, I don’t know how to start when implementing this.

**Comment by madelen-at-work** [comment]
Since the issue does not seem to be related to the operation of the Docker ACAP application as such, I suggest you ask the question in Axis Communications [Discussions](https://github.com/orgs/AxisCommunications/discussions).
You could also check the [Computer vision on device](https://developer.axis.com/computer-vision/computer-vision-on-device/develop-your-own-deep-learning-application) in the ACAP Developer Documentation.
