### ISSUE TITLE
Compatibility instructions in README

### ISSUE THREAD

**Issue by mattias-kindborg-at-work** [AxisCommunications/docker-acap#55]
Regarding the compatibility instructions in README.md, perhaps we should consider adding information that you need to enable SSH (with link to existing instructions, or have the instructions here in the repo) on the device before attempting to run the command.

One might otherwise, falsely, assume that the camera hasn't support for Docker, while it in fact doesn't allow SSH connections.

**Comment by pppaulpeter** [comment]
> Regarding the compatibility instructions in README.md, perhaps we should consider adding information that you need to enable SSH (with link to existing instructions, or have the instructions here in the repo) on the device before attempting to run the command.
> 
> One might otherwise, falsely, assume that the camera hasn't support for Docker, while it in fact doesn't allow SSH connections.

agree, have you try the tls connection? any problem?

**Comment by mattias-kindborg-at-work** [comment]
The configuration went fine, got the ACAP running on the camera.
