### ISSUE TITLE
it seems the tls certificate is not working on my camera

### ISSUE THREAD

**Issue by pppaulpeter** [AxisCommunications/docker-acap#56]
Hi,
after i creating the server certificate following this guider https://docs.docker.com/engine/security/protect-access/
and copy them to camera and enable the tls funtion, but the camera still complain error as the following log shows:
(base) ubuntu@ubuntu-XPS-8930:~/Downloads/axis_sourcecode/acap4/acap-computer-vision-sdk-examples/hello-world$ docker --tlsverify        --tlscacert=./ca.pem        --tlscert=./cert.pem        --tlskey=./key.pem   -H=10.199.27.172:2376  version
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu5~18.04.3
 Built:             Mon Nov  1 01:04:14 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
The server probably has client authentication (--tlsverify) enabled. Please check your TLS client certification settings: Get https://10.199.27.172:2376/v1.24/version: remote error: tls: bad certificate
any thoughts?should i reboot the camera when i enable the tls funtion?

**Comment by jojju** [comment]
Hi,
Could you try using the latest_beta-[aarch64/armv7hf] version and see if it makes a difference?
You shouldn't have to reboot the camera. You shouldn't have to restart the ACAP either but you can try it and see if it helps if you haven't already done so.

**Comment by pppaulpeter** [comment]
> 

the latest firmware version? could you provide me the download link?
