### ISSUE TITLE
Better error handling of devices without container support

### ISSUE THREAD

**Issue by pataxis** [AxisCommunications/docker-acap#65]
### Describe the feature

Installing and starting the **docker-acap** on a device without container support gives this output in the system log,

```
[ ERR ] acapctl: code 1: ../git/src/util.c:454: Failed running "systemctl restart --quiet 'sdkdockerdwrapper.service'"
[ WARNING ] acapmanager: acapmanager-dbus.c:1109 Failed to start dockerdwrapper
[ WARNING ] acapmanager: acapmanager-dbus.c:381 acapctl error 1: Internal error, contact maintainer.
```
which doesn't explain what the problem is.

A quick way to get more information in the system log would be to check for container support in postinstall script and print an error message. This will probably not stop the output above but could give additional information that container support is missing on this device.

A better way could be to not even install the application, but uncertain how much work it would involve.

### Added value

I think it would be valuable to have a better handling when the device lacks container support

**Comment by david-molnar-oculai** [comment]
Is there a list of supported devices?

**Comment by madelen-at-work** [comment]
Hi @david-molnar-oculai  
Supported devices can be found on the Axis.com [Product Selctor](https://www.axis.com/support/tools/product-selector/shared/%5B%7B%22index%22%3A%5B4%2C2%5D%2C%22value%22%3A%22Yes%22%7D%5D) page, by selecting `container support` under `Hardware platform` in the menu on the left.
