### ISSUE TITLE
Failed on connection through docker 

### ISSUE THREAD

**Issue by rose-jinyang** [AxisCommunications/docker-acap#77]
Hello
How are you?
Thanks for contributing to this project.

I have my AXIS camera.
I checked that this is a container capable device and 2 ACAP applications are already installed and they can run on the camera device through the web interface.

![image](https://user-images.githubusercontent.com/47862419/185167893-26134e35-2526-4834-85b0-7a5fe80c7a01.png)

I tried to run the following command on my desktop PC (Ubuntu 20.04).

docker -H=x.x.x.x:2375 version

But I met the following issue.

![image](https://user-images.githubusercontent.com/47862419/185168788-427464fa-3a97-44fd-871f-a4d5f6f2122c.png)

How should I fix this issue?
Thanks

**Comment by Corallo** [comment]
If the app doesn't appear in the list of app, it means that you don't have docker acap installed yet.
Proceed installing it as explained in the readme before running docker commands.

**Comment by rose-jinyang** [comment]
Thanks for quck reply.
Yeah, it is right.
First, the docker acap should be installed.
Here what is important is that the docker acap should be installed from the pc on the same local network rather than Internet.
Thanks
